
const produtos = [{id:'camiseta-juka',nome:'Camiseta Juka',preco:79.9},{id:'caneca-juqui',nome:'Caneca Juqui',preco:49.9},{id:'ecobag-mata',nome:'Eco Bag Mata',preco:39.9}];
const userWhats = '5511997611042';
let carrinho = [];
function renderProdutos(){ const el = document.getElementById('produtosLista'); if(!el) return; el.innerHTML=''; produtos.forEach(p=>{ const card = document.createElement('div'); card.className='card'; card.innerHTML = `<h4>${p.nome}</h4><p>R$ ${p.preco.toFixed(2).replace('.',',')}</p><button data-id="${p.id}" class="btn btn-primary add-cart">Adicionar</button>`; el.appendChild(card); }); el.querySelectorAll('.add-cart').forEach(b=> b.addEventListener('click', (e)=>{ addToCart(e.currentTarget.getAttribute('data-id')); }));}
function addToCart(id){ const it = carrinho.find(i=>i.id===id); if(it) it.qtd++; else carrinho.push({id,qtd:1}); renderCart(); }
function renderCart(){ const el = document.getElementById('carrinhoItens'); const totalEl = document.getElementById('carrinhoTotal'); if(!el) return; el.innerHTML=''; if(!carrinho.length){ el.innerHTML='<p class="muted">Carrinho vazio</p>'; totalEl.textContent='R$ 0,00'; return; } let total=0; carrinho.forEach(it=>{ const p = produtos.find(x=>x.id===it.id); const sub = p.preco*it.qtd; total+=sub; const row = document.createElement('div'); row.className='carrinho-item'; row.innerHTML = `<span>${it.qtd}x ${p.nome}</span><span>R$ ${sub.toFixed(2).replace('.',',')}</span><button class="btn-link" data-remove="${it.id}">remover</button>`; el.appendChild(row); }); document.querySelectorAll('[data-remove]').forEach(b=> b.addEventListener('click',(e)=>{ const id=e.currentTarget.getAttribute('data-remove'); carrinho = carrinho.filter(x=>x.id!==id); renderCart(); })); totalEl.textContent = 'R$ ' + total.toFixed(2).replace('.',','); }
document.addEventListener('DOMContentLoaded', ()=>{ renderProdutos(); renderCart(); document.getElementById('btnCheckout')?.addEventListener('click', ()=>{ document.getElementById('donationModal').style.display='flex'; }); document.getElementById('donateCancel')?.addEventListener('click', ()=>{ document.getElementById('donationModal').style.display='none'; sendOrder('0'); }); document.getElementById('donateConfirm')?.addEventListener('click', ()=>{ const v = document.getElementById('donationValue').value || '0'; document.getElementById('donationModal').style.display='none'; sendOrder(v); }); });
function sendOrder(donation){ if(!carrinho.length){ alert('Carrinho vazio'); return; } let msg = 'Quero fechar meu pedido:%0A'; let total=0; carrinho.forEach(it=>{ const p = produtos.find(x=>x.id===it.id); const sub = p.preco*it.qtd; total+=sub; msg += `- ${it.qtd}x ${p.nome} (R$ ${p.preco.toFixed(2).replace('.',',')})%0A`; }); if(donation && donation!=='0') msg += `%0A+ Doação Amor Animal: R$ ${donation} (PIX: amoranimaljuquitiba@gmail.com)%0A`; msg += `%0ATotal aproximado: R$ ` + total.toFixed(2).replace('.',',') + `%0A%0AQuero fechar meu pedido.`; const url = `https://wa.me/${userWhats}?text=` + encodeURIComponent(msg); window.open(url,'_blank'); }
